version: "3"
services:
  db:
    image: mariadb:10.4
    container_name: "laravel-db"
    volumes: 
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
     - "3306:3306"
  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./source:/var/www/html
      - .php/vhosts.conf:/etc/apache2/conf-enabled/vhosts.conf
    ports:
     - "8080:80"
